### PR TITLE
🐛 Fix compatibility issues with Node.js 12.x

### LINKED ISSUE #32: npm install sha3 fails - node10/npm6
Traceback:
> sha3@1.2.0 install /Users/noahzinsmeister/Documents/github/smart-contracts/snowflake_poc/node_modules/sha3
> node-gyp rebuild

  CXX(target) Release/obj.target/sha3/src/addon.o
../src/addon.cpp:59:36: error: no matching member function for call to 'NewInstance'
                        info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                  ~~~~~~^~~~~~~~~~~
/Users/noahzinsmeister/.node-gyp/10.0.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/noahzinsmeister/.node-gyp/10.0.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/noahzinsmeister/Documents/github/smart-contracts/snowflake_poc/node_modules/sha3
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

### PR DESCRIPTION
**Pull request by canterberry**
Some deprecated function calls had been removed in the Node.js V8 APIs, so needed to upgrade those.
Resolves #32 and #50 by providing a native C implementation (1.x) compatible with Node.js 12.x.

 * :package: Upgraded the **nan** package, which resolved some transitive compatibility issues.
 * :bug: Replaced deprecated+removed `GetFunction()` calls with `GetFunction(context).ToLocalChecked()`.
 * :bug: Replaced deprecated+removed `->ToInt32Value()` call with `.As<Int32>()->Value()`.

**This PR intends to introduce no functional changes.** It serves only to contain compatibility fixes specifically for the 1.x implementation, so upon merge would result in a patch version increment of that branch to **1.2.3**.

To support this, a new [`v1.x`](https://github.com/phusion/node-sha3/tree/v1.x) branch has been created, to which this PR aims to be merged. This affects only the native C implementation, so no changes are needed on the `master` (2.x) branch.

References:

 * [V8 Reference](https://v8docs.nodesource.com/node-8.11/db/d85/classv8_1_1_object.html)
 * [nan](https://github.com/nodejs/nan/)

### CODE REVIEW

**Comment by canterberry** [comment]
Ignore the CircleCI build error -- the 1.x branch does not have a CircleCI configuration.

> :bulb: In fact, neither does 2.x, but even though org-level admin privileges are not necessary to *start building* a project to CircleCI, they are necessary to *stop building* the project.

**Comment by canterberry** [comment]
cc @davidmurdoch and @bytezantium, who reported the 12.x compatibility issue. The steps in [this comment](https://github.com/phusion/node-sha3/issues/32#issuecomment-490157571), when used with version `1.2.3` (after this PR is merged and the resulting version is published), should serve as a workaround for web3 installation issues until other packages have had a chance to update their versions.

File: src/addon.cpp [hunk 1]
```diff
@@ -66,35 +66,39 @@ class SHA3Hash: public ObjectWrap {
...
 	static
 	NAN_MODULE_INIT(Init) {
-		Local<FunctionTemplate> t = Nan::New<FunctionTemplate>(New);
-		t->SetClassName(Nan::New<String>("SHA3Hash").ToLocalChecked());
-		t->InstanceTemplate()->SetInternalFieldCount(1);
+		Local<Context> context = target->CreationContext();
 
-		Nan::SetPrototypeMethod(t, "update", Update);
-		Nan::SetPrototypeMethod(t, "digest", Digest);
+		Local<String> className = Nan::New<String>("SHA3Hash").ToLocalChecked();
```
Comment (canterberry) [inline src/addon.cpp]: :memo: **Implementation Note:** Previously, this was being computed and used twice (L70 and L77).

File: src/addon.cpp [hunk 2]
```diff
@@ -66,35 +66,39 @@ class SHA3Hash: public ObjectWrap {
...
 
-		constructor.Reset(t->GetFunction());
-		target->Set(Nan::New<String>("SHA3Hash").ToLocalChecked(), t->GetFunction());
+		Local<FunctionTemplate> functionTemplate = Nan::New<FunctionTemplate>(New);
+
+		functionTemplate->SetClassName(className);
+		functionTemplate->InstanceTemplate()->SetInternalFieldCount(1);
+
+		Nan::SetPrototypeMethod(functionTemplate, "update", Update);
+		Nan::SetPrototypeMethod(functionTemplate, "digest", Digest);
```
Comment (canterberry) [inline src/addon.cpp]: :memo: **Implementation Note:** This is the same as the previous L73 and L74 -- `t` was renamed to `functionTemplate` for clarity.

File: src/addon.cpp [hunk 3]
```diff
@@ -66,35 +66,39 @@ class SHA3Hash: public ObjectWrap {
...
+		Isolate *isolate = info.GetIsolate();
+		Local<Context> context = isolate->GetCurrentContext();
 		SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(info.This());
 
 		ASSERT_IS_STRING_OR_BUFFER(info[0]);
-#if NODE_VERSION_AT_LEAST(0,11,0)
 		enum Nan::Encoding enc = static_cast<Nan::Encoding>(ParseEncoding(Isolate::GetCurrent(), info[0], node::BINARY));
-#else
-		enum Nan::Encoding enc = static_cast<Nan::Encoding>(ParseEncoding(info[0], node::BINARY));
-#endif
```
Comment (canterberry) [inline src/addon.cpp]: :memo: **Implementation Note:** This (and the other conditional on L122) has been removed because these very old versions of Node.js (< v0.11.0) are no longer supported.

File: src/addon.cpp [hunk 4]
```diff
@@ -66,35 +66,39 @@ class SHA3Hash: public ObjectWrap {
...
+
+		Local<Function> f = functionTemplate->GetFunction(context).ToLocalChecked();
+		constructor.Reset(f);
+		target->Set(className, f);
 	}
 
 	static
 	NAN_METHOD(Update) {
+		Isolate *isolate = info.GetIsolate();
+		Local<Context> context = isolate->GetCurrentContext();
```
Comment (canterberry) [inline src/addon.cpp]: :memo: **Implementation Note:** This `context` is now required for `ToObject()` down below.

File: src/addon.cpp [hunk 5]
```diff
@@ -66,35 +66,39 @@ class SHA3Hash: public ObjectWrap {
 
 	static
 	NAN_MODULE_INIT(Init) {
-		Local<FunctionTemplate> t = Nan::New<FunctionTemplate>(New);
-		t->SetClassName(Nan::New<String>("SHA3Hash").ToLocalChecked());
-		t->InstanceTemplate()->SetInternalFieldCount(1);
+		Local<Context> context = target->CreationContext();
```
Comment (canterberry) [inline src/addon.cpp]: :memo: **Implementation Note:** This `context` is now required for `GetFunction()` down below.

**Comment by canterberry** [comment]
Given that this issue is actively blocking some *web3* users, I'm going to go ahead and merge this to push a v1.2.3 release. I'll continue to monitor for any emergent issues, and if anything comes up, v1.2.2 and v2.0.2 are still available.
